### ISSUE TITLE
Error reading macros from M908

### ISSUE THREAD

**Issue by daddi79** [dokutan/mouse_m908#3] opened 2020-09-07 19:26 UTC
Hi,
    I'm an Arch user and I've a brand new Redragon M908. 
Reading mouse config with `mouse_m908 -R config_2.ini` generate the file correctly.
When I read file contents I see

> ;## macro1
> ;# unknown, please report as bug: 81 1 0
> ;# up   mouse_left

The second line should be simply a `down mouse_left`  command that I've previously sent to the device with `mouse_m908 -m ./macro_click.macro -n 1`.

This file contains only

> down    mouse_left
> up      mouse_left

There is something that I'm doing wrong or there is a bug to watch for?

Thanks in advance!

**Comment by dokutan** [comment] 2020-09-07 21:39
Thanks for opening this issue, this was indeed a bug in the macro decoding you found. I could reproduce this behaviour, the most recent commit i made should fix it (it did for my at least). Feel free to close this issue if it works for you, otherwise i will continue looking into this.

PS: i don't know what setup you are trying to achieve, but if you want to map a button as a left click you can simply use
```
button_12=left
```
in your configuration (obviously replace button_12 with the right one).

**Comment by daddi79** [comment] 2020-09-08 00:47
Thanks for your response! 
With the latest commit everything works fine for me, the issue can be closed :)

I'm trying to create a more complex macro, the example that I've provided was the simpliest where the issue could be found.

Thank you!

**Comment by dokutan** [comment] 2020-09-08 01:54
Perfect, then i am closing this.

**Closed by dokutan** 2020-09-08 01:54 UTC
Labels: bug

**Comment by LeoJohnsom** [comment] 2025-06-22 15:57
Hello, I've recently had problems with my m908 software. At first, I didn't have any problem, but after resetting my pc due to a RAT, I've downloaded the software again, resulting to the loss of my macros. After downloading the software again and putting all the macros, it all comes down to the last part, saving the macros, so that the mouse actually works, however, it seems after clicking on " save ", the loading bar keeps being stuck at 30% , then the application just closes without the macro buttons actually doing anything after. Please, help me fix this.
Thank you!
